### ISSUE TITLE
Syntax Error on headers = {"Authorization": f"token {TOKEN}"}

### ISSUE THREAD

**Issue by Piyush-Chaudhary** [VishalRamesh50/Github-Environment-Cleaner#1]
After running **python3 delete_environment.py** in the terminal, it's throwing 

`File "delete_environment.py", line 13
    headers = {"Authorization": f"token {TOKEN}"}
                                               ^
SyntaxError: invalid syntax`

**Comment by VishalRamesh50** [comment]
Are you sure `python3` is pointing to a valid python3 version? This script will not work with `python2`. You can check the version with `python3 -V`. You will need at least a python version 3.6 since that is when f-strings were introduced.

**Comment by Piyush-Chaudhary** [comment]
Okay, you were right. I was using python3.5.2 initially but after switching to 3.6 ubuntu 16.04 has its own issues that terminal won't open again as Gnome is using python3.5. 

Due to this [bug](https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1631367) ubuntu 16.04 is having an issue with python 3.6.

I was although resolve my terminal issue with the help of the  [blog](https://medium.com/@aaditya.chhabra/not-able-to-launch-terminal-ubuntu-16-04-84de95ecdaa) in medium and after doing this my desktop got blank with just only wallpaper, then I found this [answer](https://askubuntu.com/questions/760356/ubuntu-16-04-unity-no-desktop-just-background-wallpaper).

And now again I installed python 3.6.11 and did not close the terminal so that I can switch again to 3.5.2 by running 
`sudo rm /usr/bin/python3` 
`sudo ln -s python3.5 /usr/bin/python3`

And it's still giving some error like 
`Traceback (most recent call last):
  File "delete_environment.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'`

I tried to install dotenv with many answers in stack and google but not successful. 
Help, please!

**Comment by VishalRamesh50** [comment]
Just to confirm are you running the script with the 3.6+ version? I'm not exactly sure what you were trying to do when you said you wanted to switch back to 3.5.2. Maintaining multiple python version with pip can get messy so your dependencies might be getting a bit messed up. I would recommend using a tool such as `pyenv` if you want to maintain multiple python versions, but for now I can try to give some suggestions.

I'm assuming you tried to install the requirements with both `pip install` and `pip3 install`. If you haven't yet, I would try something like this:
```
pip3 install -r requirements.txt
```

I'm also assuming that the `requests` package was installed successfully and only the `python-dotenv` is having some issue from the way you describe the issue.

I would run `pip freeze` and `pip3 freeze` just to check if `requests` and `python-dotenv` are there or if they are missing.

If you still don't see `python-dotenv` in either of these lists you can try targeting the specific version of python when installing your dependencies doing something like:
```
pip3.6 install -r requirements.txt
```

And then hopefully when you run `pip3.6 freeze` you should see both dependencies and then you can run the script using `python3` (if that is the correct 3.6+ version). To be more specific you can run it using `python3.6`

**Comment by Piyush-Chaudhary** [comment]
Thanks, dear. It works now and I said that I wanted to switch back to python3.5.2 because every ubuntu 16.04 version user is going to do so as I have already mentioned in my last comment that there is some issue with python3.6 and gnome-terminal of ubuntu 16.04.
 Although your last comment helped me to work with your project with the help of pip3 command as I executed before only 
`pip install -r requirements.txt`

I install pip3 with `sudo apt-get install python3-pip` and then run the above command.

what you have mentioned in **README.md**.

I think you should mention the minimum version needed python3.6 and pip3 in the README.md (_Suggestion only_)

Although after running `python3 delete_environment.py`, I am getting now
`Retrieving all deployments... ` 
`Could not find a repo named "xxxxxx" owned by "Piyush-Chaudhary"`

I have created a [new ticket](https://github.com/VishalRamesh50/Github-Environment-Cleaner/issues/2) for this as I think this is because of the Private Repo.
