### ISSUE TITLE
Private repo giving Could not find a repo named "repo_name" owned by "username"

### ISSUE THREAD

**Issue by Piyush-Chaudhary** [VishalRamesh50/Github-Environment-Cleaner#2]
After running the command `python3 delete_environment.py` 
I am getting  
`Retrieving all deployments...`
`Could not find a repo named "repo_name" owned by "Username"` 
I think this is because of the private repo but as I am the owner of the repo, it should run, don't you think? Or should there is some extra step to be run, which I am missing now?

**Comment by VishalRamesh50** [comment]
Yes, as long as the you are the owner of the repository it should just work even if they are private repositories. I would just ask to make sure that you are spelling the repository and username correctly. Make sure you are not using an underscore if there is a dash in the name, etc. The repo name should match the name that you find on GitHub, not the a directory name on your computer. Also ensure that you've given the token the correct scope: `repo_deployment`

**Comment by Piyush-Chaudhary** [comment]
I have checked all the listed steps again and everything is fine with all of the requirements needed, but still getting the same error.
I also want to mention a thing that the repo is under the organisation and I am the owner of the organisation as well as the repo both. 

Is this something related to the issue, the organisational thing?

**Comment by VishalRamesh50** [comment]
Aha, in that case I would try using the organization name instead of your username because that is the "owner" of the repository. Perhaps I can change the prompt to make this clearer.

**Comment by Piyush-Chaudhary** [comment]
Hey, great bro. It works.
Yes, you should make the README.md more clearer.
Thanks a lot, although I am not a python guy but the sibling one (**RUBY**) :see_no_evil: , I have learned a lot in 2 days about the python.
