### ISSUE TITLE
Work on private repos ?

### ISSUE THREAD

**Issue by Chanonry** [VishalRamesh50/Github-Environment-Cleaner#6]
Program runs as described but I get an error:

Could not find a repo named "nk-actions-deployments" owned by "Chanonry"

It definitely exists but is private.  The token has the correct permissions so not sure why else this would not work

**Comment by VishalRamesh50** [comment]
It's designed to work with private repos as well. Is this repo under an organization or an account named Chanonry?

**Comment by Chanonry** [comment]
Account named Chanonry. May be more of an issue with the status of the deployment hence not finding it. When I make a curl request as per the docs I get a similar response.

Looks like the problem is at my end !
